spring.application.name=dr3-tp3
server.port=8080

external.api.entities.url=https://apichallenges.eviltester.com/sim/entities
external.api.simpleapi.url=https://apichallenges.eviltester.com/simpleapi/items
